name: CD - Deploy to Vercel

# Trigger this workflow only on pushes to the main branch (or a deployment branch)
on:
  push:
    branches:
      - main # Only deploy from the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (replace with the version your project needs)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Adjust based on the version you are using

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Nuxt.js project
      - name: Build project
        run: npm run build

      # Step 5: Deploy the project to Vercel using the Vercel CLI
      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm
