name: CI - Build Project

# Trigger this workflow on pushes and pull requests to the specified branches
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (replace with the version your project needs)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Adjust based on the version you are using

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Nuxt.js project
      - name: Build project
        run: npm run build
